# docker-compose.yml
version: '3.1'
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: url_shortner
    volumes:
      - ./data:/var/lib/postgresql/data