version: "3.8"

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "supersecretpassword"
      POSTGRES_DB: "url_shortner"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  server:
    build:
      context: server
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    ports:
      - "5000:5000"
  # client:
  #   build:
  #     context: client/hello_uld-shortner
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - server
  #   ports:
  #   - "3000:3000"