version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: "exit 0"
    volumes:
      - ./database:/var/lib/postgresql/data
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 5000:5000
  client:
    build:
      context: ./client/hello_uld-shortner
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - 3000:3000